### ISSUE TITLE
Report clearly error message and empty connection handling

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/flow#112]
**Current behavior (how does the issue manifest):**

Let's say I have an activity which has connection field but the connection field empty

```
"input": {
                "Connection": "",
                "UpdateName": "",
                "Query": "",
                "manualmode": false,
                "RuntimeQuery": "",
                "State": "66b570f7-6938-4b46-86db-6f23dfbad989"
              },
```
Today we have a panic error, this is defect we need to fix. but for what would be correct behavior.

- Throw out properly error messages for end-user to clearly know what's going wrong
- Consider that the connection field can be an option(most case it is required), so can we just pass through it without giving the error? and let the connector handle the case

We also need to make our error message more clear for the end-user.  today when some wrong when start engine it reports

```
Failed to create engine: error unmarshalling flow: create task [PostgreSQLQuery] error: convert value [] to type [connection] error: connection config not configured
```

This is not very clear for the end-user. especially `error unmarshalling flow:`

**Expected behavior:**

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by lixingwang** [comment]
@fm-tibco Any thoughts on connection empty case?  should we pass it through or report error?

**Comment by vijaynalawade** [comment]
@fm-tibco I feel we should let contribution handle this like any other data type.
