### ISSUE TITLE
API to return parent flow instance

### ISSUE THREAD

**Issue by yxuco** [project-flogo/flow#131]
**Current behavior:**
The 'host' of subflow instance is private, and is not accessible from activities in the subflow.

**Expected behavior:**
Need a public API that an activity in the subflow can call to get the parent flow and extract flow properties of the parent scope.

**What is the motivation / use case for changing the behavior?**
The execution of my activity in a subflow depends on a property in the root parent flow, and thus in the activity I want to get the property from the activity context using the following code:
```
taskInst := ctx.(*instance.TaskInst)
parentInst := taskInst.Host() // this is the new API that exposes the parent flow instance
myValue, ok := parentInst.ActivityHost().Scope().GetValue(myProp)
```
**Additional information you deem important (e.g. I need this tomorrow):**
I have a patch for `taskinst.go` as follows, and will submit a pull request:
```
// Host returns parent flow instance
func (ti *TaskInst) Host() *TaskInst {
	h := ti.flowInst.host
	ti.logger.Debugf("got flow host: %+v", h)
	if inst, ok := h.(*TaskInst); ok {
		return inst
	}
	return nil
}
```

**Comment by lixingwang** [comment]
@yxuco  I created #130 for the same.

**Comment by lixingwang** [comment]
@yxuco  Today we can get the host from context `actionCtx := ctx.ActivityHost()` but it will only work with the same flow.  Subflow not able to get the parent flow's scope.   I created #130 yesterday to resolve the issue.

**Comment by lixingwang** [comment]
https://github.com/project-flogo/flow/pull/130  has the API ready
