### ISSUE TITLE
flow and subflow go.mod not sync

### ISSUE THREAD

**Issue by masterclock** [project-flogo/flow#39]
**Current behavior (how does the issue manifest):**
- last flow version is tagged `v0.9.2`,
- but the subflow activity go.mod is using `v0.9.0` and 
- there's no tag named `activity/subflow/v0.9.2`
this causes the flogo app cannot load subflow activities, error message shows:
`unable to resolve subflow:...`

**Expected behavior:**
can load subflow activity
**Minimal steps to reproduce the problem (not required if feature enhancement):**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
v0.9.2
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by skothari-tibco** [comment]
Can you share the sample flogo.json of what you are trying to do ? Along with your go.mod .

Thanks
